# Generated by Django 2.2.5 on 2019-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190206_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
