# Generated by Django 2.2.5 on 2019-09-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0015_auto_20190920_1520'),
        ('polled', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolledItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.RenameField(
            model_name='polled',
            old_name='is_active',
            new_name='is_done',
        ),
        migrations.AddField(
            model_name='polled',
            name='is_init',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='polled',
            name='polled_poll',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.Poll'),
        ),
    ]
