# Generated by Django 2.2.5 on 2019-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0002_auto_20190920_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polled',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
