# Generated by Django 2.2.5 on 2019-09-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0015_auto_20190920_1520'),
        ('polled', '0004_polleditemlist_polled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polleditemlist',
            options={'verbose_name': 'Polled Item List', 'verbose_name_plural': 'Polled Item Lists'},
        ),
        migrations.AddField(
            model_name='polleditemlist',
            name='quest',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.Quest'),
        ),
    ]
