# Generated by Django 2.2.5 on 2019-09-20 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0006_polled_polled_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polleditemlist',
            name='polled',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='polled.Polled'),
        ),
    ]
