# Generated by Django 2.2.5 on 2019-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0007_auto_20190921_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='polled',
            name='polled_qty_quests',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во вопросов'),
        ),
    ]
