# Generated by Django 2.2.5 on 2019-09-22 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0008_polled_polled_qty_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='polled',
            name='finish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polled',
            name='time_lim',
            field=models.PositiveIntegerField(default=0, verbose_name='время на тест. мин'),
        ),
    ]
