# Generated by Django 2.2.5 on 2019-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0011_auto_20190922_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polled',
            options={'verbose_name': 'Пройденый опрос', 'verbose_name_plural': 'Пройденые опросы'},
        ),
        migrations.AlterField(
            model_name='polled',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
