# Generated by Django 2.2.5 on 2019-09-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0014_auto_20190922_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='polleditemlist',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
