# Generated by Django 2.2.5 on 2019-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0015_polleditemlist_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='polleditemlist',
            name='qty_rights_answers',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во правильных ответов'),
        ),
    ]
