# Generated by Django 2.2.5 on 2019-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0016_polleditemlist_qty_rights_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='polleditemlist',
            name='qty_wrong_answers',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во не правильных ответов'),
        ),
    ]
