# Generated by Django 2.2.5 on 2019-10-03 15:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0018_polleditemlist_polled_item_list_bal_procent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polleditemlist',
            name='polled_item_list_bal_procent',
        ),
        migrations.AddField(
            model_name='polleditemlist',
            name='square_total_summa_global',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('100.0')), django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Бал. %'),
        ),
    ]
