# Generated by Django 2.2.5 on 2019-10-03 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0019_auto_20191003_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polleditemlist',
            name='square_total_summa_global',
        ),
        migrations.AddField(
            model_name='polleditemlist',
            name='polled_item_list_bal_procent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Бал. %'),
        ),
    ]
