# Generated by Django 2.2.5 on 2019-10-03 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0020_auto_20191003_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='polled',
            name='polled_total_perc',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='общий бал. %'),
        ),
    ]
