# Generated by Django 2.2.5 on 2019-10-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0021_polled_polled_total_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polled',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='дата завершения теста'),
        ),
        migrations.AlterField(
            model_name='polled',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='пройден полностью?'),
        ),
        migrations.AlterField(
            model_name='polled',
            name='polled_poll',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.Poll', verbose_name='опрос'),
        ),
        migrations.AlterField(
            model_name='polled',
            name='polled_user',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='тестируемый пользователь'),
        ),
        migrations.AlterField(
            model_name='polleditemlist',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='отвечен?'),
        ),
        migrations.AlterField(
            model_name='polleditemlist',
            name='quest',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.Quest', verbose_name='текст вопроса'),
        ),
    ]
