# Generated by Django 2.2.5 on 2019-12-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0023_auto_20191206_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='polleditemlistanswers',
            name='global_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Глобальная ценность'),
        ),
        migrations.AddField(
            model_name='polleditemlistanswers',
            name='local_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Локальная ценность'),
        ),
    ]
