# Generated by Django 2.2.5 on 2019-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0024_auto_20191215_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polleditemlistanswers',
            name='global_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Глобальная ценность'),
        ),
    ]
