# Generated by Django 2.2.5 on 2019-12-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polled', '0025_auto_20191215_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polled',
            options={'verbose_name': 'пройденный опрос', 'verbose_name_plural': 'пройденные опросы'},
        ),
    ]
