# Generated by Django 2.2.5 on 2019-09-09 20:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='заголовок вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя категории вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория вопросов',
                'verbose_name_plural': 'Категории вопросов',
            },
        ),
        migrations.CreateModel(
            name='QuestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quest_images/', verbose_name='Фото для вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.Quest')),
            ],
            options={
                'verbose_name': 'рисунок вопроса',
                'verbose_name_plural': 'рисуноки вопросов',
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.QuestCategory', verbose_name='категория вопроса'),
        ),
        migrations.CreateModel(
            name='PollItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_category_type', models.CharField(default='', max_length=64, verbose_name='Тип документа')),
                ('quest_capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('is_emailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.Poll')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
