# Generated by Django 2.2.5 on 2019-09-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_number',
        ),
    ]
