# Generated by Django 2.2.5 on 2019-09-09 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0002_auto_20190909_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questcategory',
            options={'verbose_name': 'категория вопросов', 'verbose_name_plural': 'категории вопросов'},
        ),
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='quest_images/', verbose_name='рисунок для вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_category_type',
            field=models.CharField(default='', max_length=64, verbose_name='категория вопросов'),
        ),
        migrations.AlterField(
            model_name='questcategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='имя категории вопроса'),
        ),
        migrations.DeleteModel(
            name='QuestImage',
        ),
    ]
