# Generated by Django 2.2.5 on 2019-09-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0004_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollitemlist',
            name='is_emailed',
        ),
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_capacity',
            field=models.PositiveIntegerField(verbose_name='Кол-во вопросов. %'),
        ),
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_category_type',
            field=models.CharField(choices=[('Сетевая архитектура', 'Сетевая архитектура'), ('Взаимодействие с клиентами', 'Взаимодействие с клиентами'), ('Диагностика проблем', 'Диагностика проблем')], default='Сетевая архитектура', max_length=256, verbose_name='категории вопросов'),
        ),
    ]
