# Generated by Django 2.2.5 on 2019-09-11 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0005_auto_20190911_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='время на тест. мин'),
        ),
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Кол-во вопросов. %'),
        ),
    ]
