# Generated by Django 2.2.5 on 2019-09-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0006_auto_20190911_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_emailed',
        ),
    ]
