# Generated by Django 2.2.5 on 2019-09-11 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0007_remove_poll_is_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_capacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Кол-во вопросов. %'),
        ),
    ]
