# Generated by Django 2.2.5 on 2019-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0008_auto_20190911_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='qwests_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, upload_to='quest_images/', verbose_name='рисунок для вопроса'),
        ),
    ]
