# Generated by Django 2.2.5 on 2019-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0009_auto_20190911_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_category_type',
            field=models.CharField(choices=[('Сетевая архитектура', 'Сетевая архитектура'), ('Взаимодействие с клиентами', 'Взаимодействие с клиентами'), ('Диагностика проблем', 'Диагностика проблем'), ('Диагностика проблем c HS', 'Диагностика проблем c HS')], default='Сетевая архитектура', max_length=256, verbose_name='категории вопросов'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.TextField(blank=True, default=None, max_length=128, null=True, verbose_name='заголовок вопроса'),
        ),
    ]
