# Generated by Django 2.2.5 on 2019-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0010_auto_20190911_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='qwests_qty',
            new_name='qwests_qty_total',
        ),
        migrations.RenameField(
            model_name='pollitemlist',
            old_name='quest_capacity',
            new_name='quest_capacity_item_list_procent',
        ),
        migrations.AddField(
            model_name='pollitemlist',
            name='quest_capacity_item_list_total',
            field=models.PositiveIntegerField(default=0, verbose_name='текущее кол-во вопросов'),
        ),
    ]
