# Generated by Django 2.2.5 on 2019-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0014_auto_20190914_2232'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='pollitemlist',
        #     name='quest_category_type',
        #     field=models.CharField(choices=[('Сетевая архитектура', 'Сетевая архитектура'), ('Взаимодействие с клиентами', 'Взаимодействие с клиентами'), ('Диагностика проблем', 'Диагностика проблем'), ('Диагностика проблем c HS', 'Диагностика проблем c HS'), ('hbkhj', 'hbkhj')], max_length=256, verbose_name='категории вопросов'),
        # ),
    ]
