# Generated by Django 2.2.5 on 2019-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0015_auto_20190920_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='заголовок вопроса'),
        ),
    ]
