# Generated by Django 2.2.5 on 2019-10-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0016_auto_20191003_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_category_type',
            field=models.ForeignKey(blank=True, default=None, max_length=128, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smena_tests.QuestCategory', verbose_name='категории вопросов'),
        ),
    ]
