# Generated by Django 2.2.5 on 2019-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0017_auto_20191019_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitemlist',
            name='quest_category_type',
            field=models.CharField(default=None, max_length=128, verbose_name='категории вопросов'),
            preserve_default=False,
        ),
    ]
