# Generated by Django 2.2.5 on 2019-10-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0018_auto_20191019_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitemlist',
            name='quest_category_title',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
