# Generated by Django 2.2.5 on 2019-10-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0019_pollitemlist_quest_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollitemlist',
            name='quest_category_title',
        ),
    ]
