# Generated by Django 2.2.5 on 2019-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0020_remove_pollitemlist_quest_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitemlist',
            name='quest_category_title',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
