# Generated by Django 2.2.5 on 2019-10-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0021_pollitemlist_quest_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='qwests_qty_total',
            field=models.PositiveIntegerField(null=True, verbose_name='всего вопросов в тесте'),
        ),
    ]
