# Generated by Django 2.2.5 on 2019-12-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena_tests', '0023_poll_name_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='name_poll',
            field=models.CharField(blank=True, default='без имени', max_length=64, null=True, verbose_name='Имя теста'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='qwests_qty_total',
            field=models.PositiveIntegerField(null=True, verbose_name='всего вопросов в тесте(заполняется автоматически)'),
        ),
    ]
